### PR TITLE
Fixed imputer shape bug

### PR DESCRIPTION
**Pull request by TayyabDev**
Fixed [ issue 19352 ](https://github.com/scikit-learn/scikit-learn/issues/19352) from sci-kit learn.

### CODE REVIEW

**Comment by TayyabDev** [comment]
Working on adding tests

**Review by davidhjh — APPROVED** [review]
Looks good to me!

**Review by Tanaan98 — APPROVED** [review]
lgtm 👍

**Comment by TayyabDev** [comment]
Added the test case, you can test it out using:

``python -m pytest -v sklearn/impute/tests/test_impute.py::test_imputer_reshape``

**Review by TonyHong95g — APPROVED** [review]

**Pull request merged**
